import Quiz from "./Components/Quiz";
import "./App.css";

function App() {

  const singleLetters = [
    ["ت", "t", false, "final"],
    ["پ", "p", false, "final"],
    ["ث", "s", false, "final"],
    ["ج", "j", false, "final"],
    ["چ", "ch", false, "final"],
    ["ح", "h", false, "final"],
    ["خ", "kh", false, "final"],
    ["ن", "n", false, "final"],
    ["م", "m", false, "final"],
    ["د", "d", false, "final"],
    ["ر", "r", false, "final"],
    ["ز", "z", false, "final"],
    ["ژ", "zh", false, "final"],
    ["ش", "sh", false, "final"],
    ["و", "v", false, "final"],
    ["ف", "f", false, "final"],
    ["ق", "gh", false, "final"],
    ["ص", "s", false, "final"],
    ["ض", "z", false, "final"],
    ["ط", "t", false, "final"],
    ["ظ", "z", false, "final"],
    ["ی", "y", false, "final"],
    ["ک", "k", false, "final"],
    ["گ", "g", false, "final"],
    ["ل", "l", false, "final"],
    ["غ", "gh", false, "final-after-non-connector"],
    ["ع", "a", false, "final-after-non-connector"],
    ["ه", "h", false, "final-after-non-connector"],
    ["ا", "a", false, "final"]
  ]
  const quiz = [
    ["ب", "b", false, "final"],
    ["ب", "b", false, "initial"],
    ["ت", "t", false, "final"],
    ["ت", "t", false, "initial"],
    ["پ", "p", false, "final"],
    ["پ", "p", false, "initial"],
    ["ث", "s", false, "final"],
    ["ث", "s", false, "initial"],
    ["ج", "j", false, "final"],
    ["ج", "j", false, "initial"],
    ["چ", "ch", false, "final"],
    ["چ", "ch", false, "initial"],
    ["ح", "h", false, "final"],
    ["ح", "h", false, "initial"],
    ["خ", "kh", false, "final"],
    ["خ", "kh", false, "initial"],
    ["ن", "n", false, "final"],
    ["ن", "n", false, "initial"],
    ["م", "m", false, "final"],
    ["م", "m", false, "initial"],
    ["د", "d", false, "final"],
    ["ر", "r", false, "final"],
    ["ز", "z", false, "final"],
    ["ژ", "zh", false, "final"],
    ["ش", "sh", false, "final"],
    ["ش", "sh", false, "initial"],
    ["و", "v", false, "final"],
    ["ف", "f", false, "final"],
    ["ف", "f", false, "initial"],
    ["ق", "gh", false, "final"],
    ["ق", "gh", false, "initial"],
    ["ص", "s", false, "final"],
    ["ص", "s", false, "initial"],
    ["ض", "z", false, "final"],
    ["ض", "z", false, "initial"],
    ["ط", "t", false, "final"],
    ["ظ", "z", false, "final"],
    ["ی", "y", false, "final"],
    ["ی", "y", false, "initial"],
    ["ک", "k", false, "initial"],
    ["ک", "k", false, "final"],
    ["گ", "g", false, "initial"],
    ["گ", "g", false, "final"],
    ["ل", "l", false, "initial"],
    ["ل", "l", false, "final"],
    ["غ", "gh", false, "final-after-connector"],
    ["غ", "gh", false, "final-after-non-connector"],
    ["غ", "gh", false, "medial"],
    ["غ", "gh", false, "initial"],
    ["ع", "a", false, "final-after-connector"],
    ["ع", "a", false, "final-after-non-connector"],
    ["ع", "a", false, "medial"],
    ["ع", "a", false, "initial"],
    ["ه", "h", false, "final-after-connector"],
    ["ه", "h", false, "final-after-non-connector"],
    ["ه", "h", false, "medial"],
    ["ه", "h", false, "initial"],
    ["ا", "a", false, "final"],
  ];
  return (
    <div className="App">
      <Quiz />
    </div>
  );
}

export default App;
